#+TITLE:RDFazer

* Introduction
RDFazer is a chrome browser plugin for tagging a website with RDFa concepts. It only tags the static page and does not store the content anywhere. It was concieved for taking an existing (static) webpage and tagging it with concepts from some taxonomy (e.g. the EC ESCO taxonomy). This page can then be stored elsewhere.

This code was written based on the nice input from:
- the tutorial provided by google :: e.g. https://developer.chrome.com/extensions/getstarted
                   
This code makes heavy use of the [[https://github.com/timdown/rangy][rangy]] library, jquery and jquery ui.

RDFazer is currently a WIP and should only be used if you know what you are doing.

* TODO
- [X] Allow search through SPARQL endpoint
- [X] Add settings panel
- [X] Build a better CSS style...
- [X] allow direct save of RDFazed html file
- [ ] allow storing query result properties as RDFa, apart from just the URI
- [ ] Build final CSS style
- [ ] Add paging to search results
- [ ] allow showing other property than URI in side bar
- [ ] add actual readme
